### ISSUE TITLE
Multiple Grades for Each Student

### ISSUE THREAD

**Issue by de-olagundoye** [WDI-Persephone-Project-3/WDI-Project-3#31]
So our group is a little stumped on how we should handle this:

Each student takes a quiz, and the quiz score is calculated. 

In order to best pull/show every quiz grade a student has earned, should we push each grade to a separate table to store and pull forever, or should we just have rails calculate each score each time to render the scores onto the show page?

TL;DR: Is it better to calculate something once and store it forever, or just calculate it each time we want to show it?

Does that even make sense?

**Comment by phlco** [comment]
``````
Phil Lamplugh [2:25 PM] 
That's a deep question.

​[2:25] 
nice issue format.

​[2:25] 
so you have a student taking a quiz and a quiz is composed of multiple questions

de olagundoye [2:25 PM] 
Yeah it’s such a mess

​[2:26] 
So

Phil Lamplugh [2:27 PM] 
well you might want to store if the response was right or not

​[2:27] 
response has a choice

​[2:27] 
you can always check that off the answer table

​[2:27] 
so when you calculate someone’s grade for a quiz

​[2:28] 
so if you’re student 7 and you took quiz 1...

​[2:28] 
we’d find all your responses in ActiveRecord

​[2:30] 
 ```responses = Response.where({student_id: 7, quiz_id 1})
``````

(edited)

​[2:31] 
then you’d want to add up all the choices, right?

de olagundoye [2:31 PM] 
Yes

​[2:32] 
But, you have led us to a breakthrough. Thank youuuuuu!!!

```
```
